package trace

// GoShimSource is the runtime half of the Go shim. It is written into a scratch
// copy of the repository, never into the repository itself: instrumentation is
// a property of a trace run, not of the code under audit.
//
// It speaks the same JSONL Event schema as the Python and Node shims, so the
// core ingests all three identically (spec §4.2).
const GoShimSource = `// Code generated by plum. DO NOT EDIT.
// Runtime half of the Go trace shim. Written into a scratch copy of the repo.
package plumtrace

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"runtime"
	"strconv"
	"sync"
	"sync/atomic"
	"time"
)

// KV is one recorded argument. Values are formatted with %v and truncated,
// because a trace is evidence, not a heap dump.
type KV struct {
	K string
	V any
}

type event struct {
	SchemaVersion string            ` + "`json:\"schema_version\"`" + `
	Kind          string            ` + "`json:\"event\"`" + `
	Symbol        string            ` + "`json:\"symbol_id\"`" + `
	InvocationID  string            ` + "`json:\"invocation_id\"`" + `
	ParentID      string            ` + "`json:\"parent_invocation_id\"`" + `
	TSNanos       int64             ` + "`json:\"ts_ns\"`" + `
	Depth         int               ` + "`json:\"depth\"`" + `
	Args          map[string]string ` + "`json:\"args,omitempty\"`" + `
	Result        string            ` + "`json:\"result,omitempty\"`" + `
	Exception     string            ` + "`json:\"exception,omitempty\"`" + `
	TestID        string            ` + "`json:\"test_id,omitempty\"`" + `
}

var (
	mu      sync.Mutex
	out     *os.File
	enc     *json.Encoder
	counter atomic.Int64
	stacks  = map[int64][]string{}
	maxEv   int64 = 200000
	written atomic.Int64
)

func init() {
	path := os.Getenv("PLUM_TRACE_OUT")
	if path == "" {
		return
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return
	}
	out, enc = f, json.NewEncoder(f)
	if v := os.Getenv("PLUM_TRACE_MAX"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil && n > 0 {
			maxEv = n
		}
	}
}

func emit(e event) {
	if enc == nil || written.Load() >= maxEv {
		return
	}
	e.SchemaVersion = "1.0"
	e.TSNanos = time.Now().UnixNano()
	e.TestID = os.Getenv("PLUM_TEST_ID")
	mu.Lock()
	_ = enc.Encode(e)
	written.Add(1)
	mu.Unlock()
}

// goid reads the goroutine id from the runtime stack header. Expensive, and
// only ever paid under instrumentation — it is what keeps concurrent frames
// from being interleaved into one nonsense stack.
func goid() int64 {
	var buf [40]byte
	n := runtime.Stack(buf[:], false)
	s := string(buf[:n])
	// "goroutine 123 [running]:"
	i := len("goroutine ")
	j := i
	for j < len(s) && s[j] >= '0' && s[j] <= '9' {
		j++
	}
	id, _ := strconv.ParseInt(s[i:j], 10, 64)
	return id
}

func truncate(s string) string {
	if len(s) > 200 {
		return s[:200] + "..."
	}
	return s
}

// Enter records a call and returns the deferred half, which records the return
// (or, when the frame is unwinding, a raise — then re-panics so behaviour is
// unchanged).
func Enter(symbol string, args ...KV) func(...any) {
	if enc == nil {
		return func(...any) {}
	}
	gid := goid()
	id := strconv.FormatInt(gid, 10) + "-" + strconv.FormatInt(counter.Add(1), 10)

	mu.Lock()
	st := stacks[gid]
	parent := ""
	if len(st) > 0 {
		parent = st[len(st)-1]
	}
	depth := len(st)
	stacks[gid] = append(st, id)
	mu.Unlock()

	m := map[string]string{}
	for _, kv := range args {
		m[kv.K] = truncate(fmt.Sprintf("%v", kv.V))
	}
	emit(event{Kind: "call", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth, Args: m})

	return func(results ...any) {
		mu.Lock()
		if st := stacks[gid]; len(st) > 0 {
			stacks[gid] = st[:len(st)-1]
		}
		mu.Unlock()

		if r := recover(); r != nil {
			emit(event{Kind: "raise", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth,
				Exception: truncate(fmt.Sprintf("%v", r))})
			panic(r) // observe, do not swallow
		}
		res := ""
		for i, r := range results {
			if i > 0 {
				res += ", "
			}
			res += fmt.Sprintf("%v", deref(r))
		}
		emit(event{Kind: "return", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth, Result: truncate(res)})
	}
}

// deref unwraps the pointers-to-named-results the injector passes in, so the
// value recorded is the value the caller actually saw.
func deref(v any) any {
	rv := reflect.ValueOf(v)
	if rv.Kind() != reflect.Ptr {
		return v
	}
	if rv.IsNil() {
		return "<nil>"
	}
	e := rv.Elem().Interface()
	if err, ok := e.(error); ok {
		if err == nil {
			return "<nil>"
		}
		return err.Error()
	}
	return e
}
`
