package trace

// GoShimSource is the runtime half of the Go shim, written into a scratch copy
// by the Go adapter (which implements trace.Rewriter).
//
// GoShimSource is the runtime half of the Go shim. It is written into a scratch
// copy of the repository, never into the repository itself: instrumentation is
// a property of a trace run, not of the code under audit.
//
// It speaks the same JSONL Event schema as the Python and Node shims, so the
// core ingests all three identically (spec §4.2).
const GoShimSource = `// Code generated by plum. DO NOT EDIT.
// Runtime half of the Go trace shim. Written into a scratch copy of the repo.
package plumtrace

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// KV is one recorded argument. Values are rendered for a person and truncated,
// because a trace is evidence, not a heap dump.
type KV struct {
	K string
	V any
}

type event struct {
	SchemaVersion string            ` + "`json:\"schema_version\"`" + `
	Kind          string            ` + "`json:\"event\"`" + `
	Symbol        string            ` + "`json:\"symbol_id\"`" + `
	InvocationID  string            ` + "`json:\"invocation_id\"`" + `
	ParentID      string            ` + "`json:\"parent_invocation_id\"`" + `
	TSNanos       int64             ` + "`json:\"ts_ns\"`" + `
	Depth         int               ` + "`json:\"depth\"`" + `
	Args          map[string]string ` + "`json:\"args,omitempty\"`" + `
	ArgsOut       map[string]string ` + "`json:\"args_out,omitempty\"`" + `
	Result        string            ` + "`json:\"result,omitempty\"`" + `
	Exception     string            ` + "`json:\"exception,omitempty\"`" + `
	TestID        string            ` + "`json:\"test_id,omitempty\"`" + `
}

var (
	mu      sync.Mutex
	out     *os.File
	enc     *json.Encoder
	counter atomic.Int64
	stacks  = map[int64][]string{}
	// tests maps a goroutine to the test it is running, so every frame beneath
	// a test carries that test's name. A test is the only artifact that is
	// named, executable, committed and about one intention — which makes it the
	// natural key for everything recorded underneath it.
	tests   = map[int64]string{}
	maxEv   int64 = 200000
	written atomic.Int64
)

func init() {
	path := os.Getenv("PLUM_TRACE_OUT")
	if path == "" {
		return
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return
	}
	out, enc = f, json.NewEncoder(f)
	if v := os.Getenv("PLUM_TRACE_MAX"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil && n > 0 {
			maxEv = n
		}
	}
}

func emit(e event) {
	if enc == nil || written.Load() >= maxEv {
		return
	}
	e.SchemaVersion = "1.0"
	e.TSNanos = time.Now().UnixNano()
	if e.TestID == "" {
		mu.Lock()
		e.TestID = tests[goid()]
		mu.Unlock()
	}
	mu.Lock()
	_ = enc.Encode(e)
	written.Add(1)
	mu.Unlock()
}

// goid reads the goroutine id from the runtime stack header. Expensive, and
// only ever paid under instrumentation — it is what keeps concurrent frames
// from being interleaved into one nonsense stack.
func goid() int64 {
	var buf [40]byte
	n := runtime.Stack(buf[:], false)
	s := string(buf[:n])
	// "goroutine 123 [running]:"
	i := len("goroutine ")
	j := i
	for j < len(s) && s[j] >= '0' && s[j] <= '9' {
		j++
	}
	id, _ := strconv.ParseInt(s[i:j], 10, 64)
	return id
}

func truncate(s string) string {
	if len(s) > 240 {
		return s[:240] + "..."
	}
	return s
}

// render formats a recorded value for someone reading evidence, rather than for
// a debugger reading memory.
//
// This used %v, which is written for the machine's convenience: it prints
// struct fields positionally so you cannot tell which is which, prints pointers
// as addresses that mean nothing once the process has exited, and spends thirty
// characters on a zero time.Time to say "unset". A single argument came out as
// an unreadable run of braces, and a value nobody can read is the same as
// having recorded nothing.
//
// So: fields are named, pointers are followed rather than printed, zero fields
// are left out because their absence is the information, and long collections
// say how many they are instead of listing them.
func render(v any) string {
	var b strings.Builder
	writeValue(&b, reflect.ValueOf(v), 0)
	return b.String()
}

const (
	renderDepth  = 3  // past this, say the shape rather than the contents
	renderItems  = 4  // elements of a slice or map before counting the rest
	renderString = 72 // characters of a string before the middle is dropped
)

func writeValue(b *strings.Builder, rv reflect.Value, depth int) {
	if !rv.IsValid() {
		b.WriteString("nil")
		return
	}
	// A type that knows how to print itself almost always prints itself better
	// than reflection can — but not at depth, where its output is what made the
	// line unreadable in the first place.
	if depth > 0 && rv.CanInterface() {
		if s, ok := rv.Interface().(fmt.Stringer); ok {
			b.WriteString(clip(s.String()))
			return
		}
		if e, ok := rv.Interface().(error); ok {
			b.WriteString(clip(e.Error()))
			return
		}
	}
	switch rv.Kind() {
	case reflect.Pointer, reflect.Interface:
		if rv.IsNil() {
			b.WriteString("nil")
			return
		}
		// The address is noise; what it points at is the evidence.
		writeValue(b, rv.Elem(), depth)
	case reflect.String:
		b.WriteString(strconv.Quote(clip(rv.String())))
	case reflect.Struct:
		writeStruct(b, rv, depth)
	case reflect.Slice, reflect.Array:
		writeList(b, rv, depth)
	case reflect.Map:
		writeMap(b, rv, depth)
	case reflect.Func, reflect.Chan, reflect.UnsafePointer:
		// Nothing about the value is legible, but whether it was set is.
		if rv.IsNil() {
			b.WriteString("nil")
			return
		}
		b.WriteString(rv.Type().String())
	default:
		if rv.CanInterface() {
			fmt.Fprintf(b, "%v", rv.Interface())
			return
		}
		fmt.Fprintf(b, "%v", rv)
	}
}

func writeStruct(b *strings.Builder, rv reflect.Value, depth int) {
	t := rv.Type()
	if depth >= renderDepth {
		b.WriteString(shortType(t) + "{...}")
		return
	}
	b.WriteString(shortType(t))
	b.WriteString("{")
	shown := 0
	for i := 0; i < rv.NumField(); i++ {
		fv := rv.Field(i)
		// A zero field is the absence of information, and printing it at full
		// width is how a struct with three set fields fills a line.
		if !fv.IsValid() || fv.IsZero() {
			continue
		}
		if shown >= renderItems {
			b.WriteString(" ...")
			break
		}
		if shown > 0 {
			b.WriteString(" ")
		}
		b.WriteString(t.Field(i).Name)
		b.WriteString(":")
		writeValue(b, fv, depth+1)
		shown++
	}
	b.WriteString("}")
}

func writeList(b *strings.Builder, rv reflect.Value, depth int) {
	if rv.Kind() == reflect.Slice && rv.IsNil() {
		b.WriteString("nil")
		return
	}
	n := rv.Len()
	// Bytes are text far more often than they are numbers.
	if rv.Type().Elem().Kind() == reflect.Uint8 && rv.Kind() == reflect.Slice && rv.CanInterface() {
		b.WriteString(strconv.Quote(clip(string(rv.Bytes()))))
		return
	}
	if n == 0 {
		b.WriteString("[]")
		return
	}
	if depth >= renderDepth {
		fmt.Fprintf(b, "[%d]", n)
		return
	}
	b.WriteString("[")
	for i := 0; i < n && i < renderItems; i++ {
		if i > 0 {
			b.WriteString(" ")
		}
		writeValue(b, rv.Index(i), depth+1)
	}
	if n > renderItems {
		fmt.Fprintf(b, " ...+%d", n-renderItems)
	}
	b.WriteString("]")
}

func writeMap(b *strings.Builder, rv reflect.Value, depth int) {
	if rv.IsNil() {
		b.WriteString("nil")
		return
	}
	n := rv.Len()
	if n == 0 {
		b.WriteString("{}")
		return
	}
	if depth >= renderDepth {
		fmt.Fprintf(b, "{%d}", n)
		return
	}
	// Sorted, so the same call twice reads the same twice. Map order is random
	// in Go, and a value that shuffles between runs cannot be compared.
	keys := rv.MapKeys()
	sort.Slice(keys, func(i, j int) bool {
		return fmt.Sprint(keys[i]) < fmt.Sprint(keys[j])
	})
	b.WriteString("{")
	for i, k := range keys {
		if i >= renderItems {
			fmt.Fprintf(b, " ...+%d", n-renderItems)
			break
		}
		if i > 0 {
			b.WriteString(" ")
		}
		fmt.Fprintf(b, "%v:", k)
		writeValue(b, rv.MapIndex(k), depth+1)
	}
	b.WriteString("}")
}

// clip drops the middle of a long string rather than the end. These are mostly
// paths and identifiers, where both ends carry meaning and the middle is the
// part you can infer.
func clip(s string) string {
	if len(s) <= renderString {
		return s
	}
	head := renderString/2 - 1
	tail := renderString - head - 3
	return s[:head] + "..." + s[len(s)-tail:]
}

// shortType drops the package qualifier. The file is already named by the
// symbol this event belongs to, so "bundle.Bundle" repeated down every line is
// width spent on something the reader already knows.
func shortType(t reflect.Type) string {
	name := t.Name()
	if name == "" {
		return ""
	}
	return name
}

// EnterTest marks the goroutine as running a named test for as long as the test
// body runs. It emits nothing itself: the test is the label on the recording,
// not a frame in it.
func EnterTest(name string) func(...any) {
	if enc == nil {
		return func(...any) {}
	}
	gid := goid()
	mu.Lock()
	previous := tests[gid]
	tests[gid] = name
	mu.Unlock()
	return func(...any) {
		mu.Lock()
		if previous == "" {
			delete(tests, gid)
		} else {
			tests[gid] = previous
		}
		mu.Unlock()
	}
}

// EnterContext records a frame the change passes through, without capturing
// anything from it. It gives the landscape the surrounding shape at a fraction
// of the cost: formatting arguments is most of what tracing spends.
func EnterContext(symbol string) func(...any) {
	if enc == nil {
		return func(...any) {}
	}
	return enter(symbol, nil, nil)
}

// Enter records a call and returns the deferred half, which records the return
// (or, when the frame is unwinding, a raise — then re-panics so behaviour is
// unchanged).
func Enter(symbol string, args ...KV) func(...any) {
	if enc == nil {
		return func(...any) {}
	}
	m := map[string]string{}
	for _, kv := range args {
		m[kv.K] = truncate(render(kv.V))
	}
	return enter(symbol, m, args)
}

// mutable reports whether a value could come back different from how it went in.
//
// Arguments are recorded on the way in, which says what a function was given
// and nothing about what it did to it. A function that fills a slice, populates
// a map or writes through a pointer changes its caller's world, and that change
// was invisible: the value the caller passed and the value it holds afterwards
// are different things, and only the first was ever recorded.
//
// Re-reading every argument on the way out would be waste, because most cannot
// have changed. A copy is a copy — an int or a string that went in one way
// cannot come back another, and re-rendering it only to compare it with itself
// costs time and finds nothing. These kinds are the ones that carry a reference
// to something the callee can reach.
func mutable(v any) bool {
	rv := reflect.ValueOf(v)
	if !rv.IsValid() {
		return false
	}
	switch rv.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Map, reflect.Interface,
		reflect.Chan, reflect.Func, reflect.UnsafePointer:
		return true
	case reflect.Struct, reflect.Array:
		// A struct is a copy, but a struct holding a pointer is a copy of a
		// handle on something shared, and writing through it is exactly how
		// most of this happens.
		return holdsReference(rv.Type(), 0)
	}
	return false
}

func holdsReference(t reflect.Type, depth int) bool {
	if depth > 3 {
		return true // cannot rule it out; assume it can change rather than miss it
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Map, reflect.Interface,
		reflect.Chan, reflect.Func, reflect.UnsafePointer:
		return true
	case reflect.Array:
		return holdsReference(t.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < t.NumField(); i++ {
			if holdsReference(t.Field(i).Type, depth+1) {
				return true
			}
		}
	}
	return false
}

func enter(symbol string, m map[string]string, args []KV) func(...any) {
	gid := goid()
	id := strconv.FormatInt(gid, 10) + "-" + strconv.FormatInt(counter.Add(1), 10)

	mu.Lock()
	st := stacks[gid]
	parent := ""
	if len(st) > 0 {
		parent = st[len(st)-1]
	}
	depth := len(st)
	stacks[gid] = append(st, id)
	mu.Unlock()

	emit(event{Kind: "call", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth, Args: m})

	return func(results ...any) {
		mu.Lock()
		if st := stacks[gid]; len(st) > 0 {
			stacks[gid] = st[:len(st)-1]
		}
		mu.Unlock()

		if r := recover(); r != nil {
			emit(event{Kind: "raise", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth,
				Exception: truncate(render(r))})
			panic(r) // observe, do not swallow
		}
		res := ""
		for i, r := range results {
			if i > 0 {
				res += ", "
			}
			res += render(deref(r))
		}
		// What the caller holds now, where that differs from what it passed.
		// Only the differences: an argument that came back the same is the
		// normal case and saying so on every line would bury the ones that did.
		var out map[string]string
		for _, kv := range args {
			if !mutable(kv.V) {
				continue
			}
			after := truncate(render(kv.V))
			if after == m[kv.K] {
				continue
			}
			if out == nil {
				out = map[string]string{}
			}
			out[kv.K] = after
		}
		emit(event{Kind: "return", Symbol: symbol, InvocationID: id, ParentID: parent, Depth: depth,
			Result: truncate(res), ArgsOut: out})
	}
}

// deref unwraps the pointers-to-named-results the injector passes in, so the
// value recorded is the value the caller actually saw.
func deref(v any) any {
	rv := reflect.ValueOf(v)
	if rv.Kind() != reflect.Ptr {
		return v
	}
	if rv.IsNil() {
		return "<nil>"
	}
	e := rv.Elem().Interface()
	if err, ok := e.(error); ok {
		if err == nil {
			return "<nil>"
		}
		return err.Error()
	}
	return e
}
`
