package claims

import (
	"bytes"
	"context"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Verdict is one claim's fate in CI. A failing claim means the doc is wrong or
// the code is — both worth knowing (spec §12).
type Verdict struct {
	Claim  Claim
	Status string // pass | fail | skipped | unverifiable
	Detail string
}

// Verify writes each executable claim's test into a scratch copy of the repo,
// beside the package that owns the claim's symbol, and runs `go test` there.
// The repository itself is never written to.
func Verify(ctx context.Context, root, scratch string, cs []Claim, copyTree func(src, dst string) error) ([]Verdict, error) {
	var out []Verdict
	var runnable []Claim
	for _, c := range cs {
		switch {
		case !c.Executable:
			// A trust-me assertion. Surfaced, never silently passed.
			out = append(out, Verdict{c, "unverifiable", "claim is tagged executable: false — this is a trust-me assertion"})
		case strings.TrimSpace(c.Test) == "":
			out = append(out, Verdict{c, "skipped", "no test body was written for this claim"})
		case c.Symbol.File() == "" || filepath.Ext(c.Symbol.File()) != ".go":
			out = append(out, Verdict{c, "skipped", "only Go claims can be executed by this runner"})
		default:
			runnable = append(runnable, c)
		}
	}
	if len(runnable) == 0 {
		return out, nil
	}

	if err := os.RemoveAll(scratch); err != nil {
		return out, err
	}
	if err := copyTree(root, scratch); err != nil {
		return out, err
	}

	byPkg := map[string][]Claim{}
	for _, c := range runnable {
		byPkg[filepath.Dir(c.Symbol.File())] = append(byPkg[filepath.Dir(c.Symbol.File())], c)
	}

	for pkgDir, pcs := range byPkg {
		pkgName, err := packageName(filepath.Join(scratch, pkgDir))
		if err != nil {
			for _, c := range pcs {
				out = append(out, Verdict{c, "skipped", err.Error()})
			}
			continue
		}
		for _, c := range pcs {
			file := filepath.Join(scratch, pkgDir, "plum_claim_"+safe(c.ID)+"_test.go")
			src := "// Code generated by plum from claims.yaml. DO NOT EDIT.\npackage " + pkgName + "\n\n" +
				importsFor(c.Test) + c.Test + "\n"
			if err := os.WriteFile(file, []byte(src), 0o644); err != nil {
				out = append(out, Verdict{c, "skipped", err.Error()})
				continue
			}
		}
		for _, c := range pcs {
			name := testFuncName(c.Test)
			if name == "" {
				out = append(out, Verdict{c, "skipped", "the test body has no func TestX(t *testing.T)"})
				continue
			}
			cmd := exec.CommandContext(ctx, "go", "test", "-run", "^"+name+"$", "-count=1", "./"+filepath.ToSlash(pkgDir))
			cmd.Dir = scratch
			var buf bytes.Buffer
			cmd.Stdout, cmd.Stderr = &buf, &buf
			if err := cmd.Run(); err != nil {
				out = append(out, Verdict{c, "fail", strings.TrimSpace(tail(buf.String(), 24))})
			} else {
				out = append(out, Verdict{c, "pass", ""})
			}
		}
	}
	return out, nil
}

var testFuncRe = regexp.MustCompile(`func\s+(Test[A-Za-z0-9_]*)\s*\(`)

func testFuncName(body string) string {
	m := testFuncRe.FindStringSubmatch(body)
	if m == nil {
		return ""
	}
	return m[1]
}

// importsFor adds the imports a generated claim test almost always needs, and
// only those it does not already declare.
func importsFor(body string) string {
	if strings.Contains(body, "import (") || strings.Contains(body, "import \"") {
		return ""
	}
	var imps []string
	if strings.Contains(body, "testing.") || strings.Contains(body, "*testing.T") {
		imps = append(imps, `"testing"`)
	}
	// The stdlib packages a claim test plausibly reaches for. A missing import
	// fails the build, and a build failure reads as a failed claim — which
	// blames the code for a gap in this list.
	for _, pkg := range []string{
		"bytes", "context", "encoding/json", "errors", "fmt", "io", "math", "os",
		"path/filepath", "reflect", "regexp", "sort", "strconv", "strings",
		"sync", "time",
	} {
		name := pkg
		if i := strings.LastIndex(pkg, "/"); i >= 0 {
			name = pkg[i+1:]
		}
		if strings.Contains(body, name+".") {
			imps = append(imps, `"`+pkg+`"`)
		}
	}
	if len(imps) == 0 {
		return ""
	}
	sort.Strings(imps)
	return "import (\n\t" + strings.Join(imps, "\n\t") + "\n)\n\n"
}

func packageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf("package dir %s: %w", dir, err)
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, parser.PackageClauseOnly)
		if err != nil {
			continue
		}
		return f.Name.Name, nil
	}
	return "", fmt.Errorf("no Go package found in %s", dir)
}

func safe(s string) string {
	var sb strings.Builder
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			sb.WriteRune(r)
		} else {
			sb.WriteByte('_')
		}
	}
	return sb.String()
}

func tail(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}
