// Package quiz is interrogation (M4). Every question is derived from a recorded
// invocation, never from prose: questions generated by an LLM from an LLM's
// documentation are comprehension theatre (P4).
package quiz

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/k3-mt/plum/internal/bundle"
	"github.com/k3-mt/plum/internal/explore"
	"github.com/k3-mt/plum/internal/trace"
)

type Question struct {
	Kind     string // return_value | next_frame | exception | cost
	Symbol   bundle.SymbolID
	Prompt   string
	Options  []string // empty ⇒ free text
	Expected string
	Source   string // what grades it, in words — shown after answering
}

// Generate builds questions for the targeted symbols, in a deterministic order
// so a re-run of the same session asks the same things.
func Generate(targets []bundle.SymbolID, events []trace.Event, l trace.Landscape, max int) []Question {
	byInvocation := map[string][]trace.Event{}
	for _, e := range events {
		byInvocation[e.InvocationID] = append(byInvocation[e.InvocationID], e)
	}
	targeted := map[bundle.SymbolID]bool{}
	for _, t := range targets {
		targeted[t] = true
	}
	onlyTargets := len(targets) > 0

	var qs []Question
	seen := map[string]bool{}
	add := func(q Question) {
		if q.Expected == "" {
			return
		}
		// One panic passes through every frame, so the same exception would
		// otherwise be asked once per frame. Ask about an outcome once.
		for _, key := range []string{
			q.Kind + "|" + string(q.Symbol) + "|" + q.Prompt,
			q.Kind + "|answer|" + normalise(q.Expected),
		} {
			if seen[key] {
				return
			}
		}
		seen[q.Kind+"|"+string(q.Symbol)+"|"+q.Prompt] = true
		seen[q.Kind+"|answer|"+normalise(q.Expected)] = true
		qs = append(qs, q)
	}

	ids := make([]string, 0, len(byInvocation))
	for id := range byInvocation {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	for _, id := range ids {
		evs := byInvocation[id]
		call := find(evs, "call")
		if call == nil || (onlyTargets && !targeted[call.Symbol]) {
			continue
		}
		if ret := find(evs, "return"); ret != nil && strings.TrimSpace(ret.Result) != "" {
			add(Question{
				Kind:     "return_value",
				Symbol:   call.Symbol,
				Prompt:   fmt.Sprintf("Given %s, what does %s return?", argString(call), call.Symbol.Qualified()),
				Expected: ret.Result,
				Source:   "recorded return value from invocation " + id,
			})
		}
		if raise := find(evs, "raise"); raise != nil {
			add(Question{
				Kind:     "exception",
				Symbol:   call.Symbol,
				Prompt:   fmt.Sprintf("Given %s, what does %s raise?", argString(call), call.Symbol.Qualified()),
				Expected: raise.Exception,
				Source:   "recorded panic from invocation " + id,
			})
		}
	}

	// Which frame is entered next — graded on the recorded call order, not on
	// what the code looks like it should do.
	enters := entered(l)
	for i := 0; i+1 < len(enters); i++ {
		if onlyTargets && !targeted[enters[i]] {
			continue
		}
		opts := choices(distinct(enters), enters[i+1], 4)
		if len(opts) < 3 {
			break
		}
		add(Question{
			Kind:     "next_frame",
			Symbol:   enters[i],
			Prompt:   fmt.Sprintf("During the traced run, which frame is entered immediately after %s?", enters[i].Qualified()),
			Options:  opts,
			Expected: enters[i+1].Qualified(),
			Source:   "recorded call order on the representative chain",
		})
	}

	// Which of these transitions cost the most — graded on Barrier.CostNanos.
	if len(l.Barriers) >= 3 {
		type bc struct {
			label string
			cost  int64
			sym   bundle.SymbolID
		}
		var all []bc
		for _, b := range l.Barriers {
			if b.FromIdx >= len(l.Wells) || b.ToIdx >= len(l.Wells) {
				continue
			}
			all = append(all, bc{
				label: l.Wells[b.FromIdx].Label + " → " + l.Wells[b.ToIdx].Label + " (" + b.Direction + ")",
				cost:  b.CostNanos,
				sym:   l.Wells[b.ToIdx].Symbol,
			})
		}
		sort.Slice(all, func(i, j int) bool { return all[i].cost > all[j].cost })
		if len(all) >= 3 {
			opts := []string{all[0].label}
			for i := len(all) - 1; i >= 1 && len(opts) < 4; i-- {
				opts = append(opts, all[i].label)
			}
			sort.Strings(opts)
			add(Question{
				Kind:     "cost",
				Symbol:   all[0].sym,
				Prompt:   "Which of these transitions cost the most in the traced run?",
				Options:  opts,
				Expected: all[0].label,
				Source:   fmt.Sprintf("recorded barrier cost %s", time.Duration(all[0].cost)),
			})
		}
	}

	return selectQuestions(qs, targeted, l, max)
}

// selectQuestions picks the set worth asking. Invocation order is not a
// priority order: three questions about the same trivial helper test nothing,
// while one question each about a risky, undocumented and targeted frame is the
// whole point of grading against traces.
func selectQuestions(qs []Question, targeted map[bundle.SymbolID]bool, l trace.Landscape, max int) []Question {
	if max <= 0 || len(qs) <= max {
		return qs
	}
	risky := map[bundle.SymbolID]bool{}
	undocumented := map[bundle.SymbolID]bool{}
	depth := map[bundle.SymbolID]int{}
	for _, w := range l.Wells {
		if w.Risk {
			risky[w.Symbol] = true
		}
		if w.Doc == "" {
			undocumented[w.Symbol] = true
		}
		if w.Depth > depth[w.Symbol] {
			depth[w.Symbol] = w.Depth
		}
	}

	base := func(q Question) float64 {
		var v float64
		if targeted[q.Symbol] {
			v += 4
		}
		if risky[q.Symbol] {
			v += 2
		}
		if undocumented[q.Symbol] {
			v += 1
		}
		if q.Kind == "exception" || q.Kind == "cost" {
			v += 1 // error propagation and cost are the things people mis-model
		}
		v += float64(depth[q.Symbol]) * 0.1
		return v
	}

	var out []Question
	usedSymbol := map[bundle.SymbolID]int{}
	usedKind := map[string]int{}
	remaining := make([]Question, len(qs))
	copy(remaining, qs)

	for len(out) < max && len(remaining) > 0 {
		best, bestScore := -1, -1e9
		for i, q := range remaining {
			score := base(q) - float64(usedSymbol[q.Symbol])*3 - float64(usedKind[q.Kind])*1.5
			if score > bestScore {
				best, bestScore = i, score
			}
		}
		q := remaining[best]
		out = append(out, q)
		usedSymbol[q.Symbol]++
		usedKind[q.Kind]++
		remaining = append(remaining[:best], remaining[best+1:]...)
	}
	return out
}

// Grade is lenient about formatting and strict about content: an answer counts
// when it names the recorded value, not when it sounds plausible.
//
// Substring matching is deliberately bounded. "b" is a substring of nearly every
// recorded value, and accepting it would turn the whole exercise into theatre —
// the failure mode P4 exists to prevent.
func Grade(q Question, given string) bool {
	want := normalise(q.Expected)
	got := normalise(given)
	if got == "" {
		return false
	}
	if len(q.Options) > 0 {
		return got == want
	}
	if got == want {
		return true
	}
	if !strings.Contains(got, want) && !strings.Contains(want, got) {
		return false
	}
	shorter, longer := len(got), len(want)
	if shorter > longer {
		shorter, longer = longer, shorter
	}
	// The answer must carry most of the recorded value, not a letter of it.
	return shorter >= 4 && float64(shorter)/float64(longer) >= 0.6
}

func normalise(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.Trim(s, `"'.,;`)
	return strings.Join(strings.Fields(s), " ")
}

func find(evs []trace.Event, kind string) *trace.Event {
	for i := range evs {
		if evs[i].Kind == kind {
			return &evs[i]
		}
	}
	return nil
}

func argString(e *trace.Event) string {
	if len(e.Args) == 0 {
		return "no arguments"
	}
	keys := make([]string, 0, len(e.Args))
	for k := range e.Args {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var parts []string
	for _, k := range keys {
		parts = append(parts, k+"="+e.Args[k])
	}
	return strings.Join(parts, ", ")
}

func entered(l trace.Landscape) []bundle.SymbolID {
	var out []bundle.SymbolID
	for _, w := range l.Wells {
		if w.Phase == "enter" {
			out = append(out, w.Symbol)
		}
	}
	return out
}

func distinct(ids []bundle.SymbolID) []bundle.SymbolID {
	seen := map[bundle.SymbolID]bool{}
	var out []bundle.SymbolID
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			out = append(out, id)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

// choices builds a small multiple-choice set: the recorded answer plus
// distractors drawn from frames that really appear in this trace. Fourteen
// options is not a question, it is a list.
func choices(pool []bundle.SymbolID, answer bundle.SymbolID, n int) []string {
	out := []string{answer.Qualified()}
	seen := map[string]bool{answer.Qualified(): true}
	// Deterministic but not adjacent: step through the pool so the distractors
	// are not simply the answer's neighbours on the chain.
	step := 1
	if len(pool) > n {
		step = len(pool) / n
	}
	for i := 0; i < len(pool) && len(out) < n; i += step {
		label := pool[i].Qualified()
		if !seen[label] {
			seen[label] = true
			out = append(out, label)
		}
	}
	for i := 0; i < len(pool) && len(out) < n; i++ {
		label := pool[i].Qualified()
		if !seen[label] {
			seen[label] = true
			out = append(out, label)
		}
	}
	sort.Strings(out)
	return out
}

// MissFor turns a wrong answer into the record that accumulates over months.
func MissFor(sessionID string, q Question, given string) explore.Miss {
	return explore.Miss{
		SessionID: sessionID, Symbol: q.Symbol, Kind: q.Kind,
		Question: q.Prompt, Expected: q.Expected, Given: given,
	}
}

// Summarise aggregates misses into the sentence no document provides.
func Summarise(ms []explore.Miss) []string {
	byKind := map[string]int{}
	for _, m := range ms {
		byKind[m.Kind]++
	}
	var kinds []string
	for k := range byKind {
		kinds = append(kinds, k)
	}
	sort.Slice(kinds, func(i, j int) bool { return byKind[kinds[i]] > byKind[kinds[j]] })

	phrase := map[string]string{
		"return_value": "mis-predict what this codebase's functions return",
		"next_frame":   "mis-predict this codebase's control flow",
		"exception":    "mis-predict this codebase's error propagation",
		"cost":         "mis-predict where this codebase spends its time",
	}
	var out []string
	for _, k := range kinds {
		p := phrase[k]
		if p == "" {
			p = "miss questions of kind " + k
		}
		out = append(out, fmt.Sprintf("%d× you %s", byKind[k], p))
	}
	return out
}
